pip install selenium
pip install requests
pip install undetected_chromedriver
pip install pyautogui
pip install pynput
pip install pywin32
pip install pyperclip
pip install ctypes
pip install colorama
pip install discord_webhook
pip install json
pip install pyarmor